version: '3'

networks:
  micro_network:
    external:
      name: micro_network

services:
  web_api:
    build: .
    image: rostegg/flask-api-boilerplate
    volumes: 
      - ./app:/app
    ports:
      - "5000:5000"
    networks:
      - micro_network
    container_name: web_api
            
